### PR TITLE
Updated french translations

### PR DESCRIPTION
**Pull request by mtancoigne**
Hi !
Everything is in the title, I translated most of the french descriptions. There are maybe 2 or 3 missing, as I don't have the real contest to test them.

### CODE REVIEW

**Comment by geobarrod** [comment]
I'll analyze your changes and then upload the new release. Let me know if you want to be added to the list of contributors, if so, send me your name and email. Thank you very much for your contribution.

**Comment by geobarrod** [comment]
@mtancoigne Please update your branch and resolve the conflicts. Thanks.

**Comment by mtancoigne** [comment]
No problem, i'll do :)

**Comment by mtancoigne** [comment]
I kept your new IT translations and my french ones. Tell me if you need another change...
If you want to add me in the contributions, it' Manuel Tancoigne, and the email is in the commits.

**Pull request merged**
